# Generated by Django 4.2 on 2026-02-08 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_barres", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("prix_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taux_tva",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        choices=[
                            ("piece", "Pièce"),
                            ("kg", "Kilogramme"),
                            ("litre", "Litre"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                ("stock_actuel", models.IntegerField(default=0)),
                ("stock_minimum", models.IntegerField(default=5)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "carte_fidelite",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_facture", models.CharField(max_length=50, unique=True)),
                ("date_facture", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cb", "Carte Bancaire"),
                            ("cheque", "Chèque"),
                            ("mixte", "Mixte"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("annulee", "Annulée"),
                            ("avoir", "Avoir"),
                        ],
                        default="valide",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facturation.client",
                    ),
                ),
                (
                    "facture_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facturation.facture",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("taux_tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facturation.article",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="facturation.facture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facturation.categorie",
            ),
        ),
    ]
